### ISSUE TITLE
Error: PostCSS plugin tailwindcss requires PostCSS 8.

### ISSUE THREAD

**Issue by zOrchid** [Karbust/Metin2-Patcher-Electron#4]
Hi Karbust,

Can you please help me with this error? I been trying for 2 hours.
 

> ./src/css/index.css (./.yarn/$$virtual/css-loader-virtual-7a45157379/0/cache/css-loader-npm-4.3.0-33464197c9-1f441ac567.zip/node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./.yarn/cache/postcss-loader-npm-3.0.0-f4ab99b685-50b2d8892d.zip/node_modules/postcss-loader/src??postcss!./src/css/index.css)
> Error: PostCSS plugin tailwindcss requires PostCSS 8.
> Migration guide for end-users:
> https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

**Comment by Karbust** [comment]
I wasn't able to reproduce this error.

The steps I followed for a brand new installation:
```
git clone https://github.com/Karbust/Metin2-Patcher-Electron/
yarn install
yarn run start
```

And Create React App doesn't support PostCSS 8 as stated on the [TailwindCSS's page](https://tailwindcss.com/docs/guides/create-react-app):

> Create React App doesn't support PostCSS 8 yet so you need to install the Tailwind CSS v2.0 PostCSS 7 compatibility build for now as we've shown above.
