### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by DemOnJR** [Karbust/Metin2-Patcher-Electron#6]
Sorry but it will be great a Video Tutorial not just for me but this updater is something new, and many people don't know how to install or use it.

**Comment by Karbust** [comment]
Done

#7

**Comment by ImKraier** [comment]
A Linux version might be great. Same, not just for me.

**Comment by Karbust** [comment]
> A Linux version might be great. Same, not just for me.

Technically speaking, you just need to add a new build option on package.json to also build to linux.
You may also need to adjust the directories on worker.ts to handle linux's paths.
